config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :flight_plans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/flight_plans/delete_all', to: 'flight_plans#delete_all'
  post '/flight_plans/download', to: 'flight_plans#download'
  post '/flight_plans/:id/run', to: 'flight_plans#run', as: 'run_flight_plan'
  post '/flight_plans/:id/submit', to: 'flight_plans#submit', as: 'submit_flight_plan'

  get '/test_api/*email/directions', to: 'test_api#directions'
  get '/test_api/*email/location/*x/*y', to: 'test_api#location'
end

app/models/application_record.rb
# frozen_string_literal: true

# Rails standard base class for application
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
   belongs_to :flight_plan
end

app/models/flight_plan.rb
class FlightPlan < ApplicationRecord
  has_many :directions, dependent: :destroy
end

app/models/location.rb
# Specifies position in terms of coordinates
class Location
  attr_accessor :x, :y, :facing

  FACING_TRANSITIONS = {
    north: {
      left: :west,
      right: :east
    },
    west: {
      left: :south,
      right: :north
    },
    east: {
      left: :north,
      right: :south
    },
    south: {
      left: :east,
      right: :west
    },
  }

  MOVEMENT_DELTAS = {
    forward: {
      north: [0,1],
      west: [-1,0],
      east: [1,0],
      south: [0,-1],
    }
  }

  def initialize
    @x = 0
    @y = 0
    @facing = :north
  end

  def update(direction)
    case direction&.type
    when "Turn"
      update_facing direction.instruction.to_sym
    when "Movement"
      update_position direction
    else
      raise "invalid type for direction: #{direction&.type}"
    end
  end

  def position
    [self.x, self.y]
  end

  def position=(coords)
    @x = coords.first
    @y = coords.last
  end

  private

  def update_facing(instruction)
    self.facing = FACING_TRANSITIONS[self.facing][instruction]
  end

  def update_position(direction)
    (1..direction.distance).each do
      self.position = [self.x, self.y].map.with_index do |pos, index|
        pos + MOVEMENT_DELTAS
                .fetch(direction&.direction&.to_sym)
                &.fetch(self.facing)
                &.at(index)
      end
    end
  end
end

app/models/movement.rb
class Movement < Direction
  enum direction: [:forward]
  def initialize(*params)
    defaults = { distance: 1}
    params[0] = defaults.merge(params[0] || {} )
    super(*params)
  end
end

app/models/turn.rb
class Turn < Direction
  enum instruction: [:left, :right]
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/flight_plans_controller.rb
class FlightPlansController < ApplicationController
  before_action :set_flight_plan, only: [:show, :edit, :update, :destroy, :run, :submit]
  DEFAULT_EMAIL = 'ragnarcom@googlemail.com'

  # GET /flight_plans
  # GET /flight_plans.json
  def index
    @flight_plans = FlightPlan.order(id: :desc)
    @email = DEFAULT_EMAIL
  end

  # POST /flight_plans/delete_all
  def delete_all
    FlightPlan.destroy_all
    redirect_to flight_plans_path
  end

  # POST /flight_plans/download
  def download
    email = params.require([:email]).first
    raise "Bad email address" unless email.match URI::MailTo::EMAIL_REGEXP
    FlightPlanDownloader.new(Api.new(Client.new(email: email))).download
    redirect_to flight_plans_path
  end

  # POST /flight_plans/1/run
  def run
    FlightPlanRunner.new(@flight_plan).run
    redirect_to flight_plans_path
  end

  def submit
    unless @flight_plan.final_x_location && @flight_plan.final_y_location
      raise "missing x or y final locations #{@flight_plan}"
    end
    email = params.require([:email]).first
    raise "Bad email address" unless email.match URI::MailTo::EMAIL_REGEXP
    @api_response = Api.new(Client.new(email: email))
                      .location(@flight_plan.final_x_location,
                                @flight_plan.final_y_location)
  end

  # GET /flight_plans/1
  # GET /flight_plans/1.json
  def show
  end

  # GET /flight_plans/new
  def new
    @flight_plan = FlightPlan.new
  end

  # GET /flight_plans/1/edit
  def edit
  end

  # POST /flight_plans
  # POST /flight_plans.json
  def create
    @flight_plan = FlightPlan.new(flight_plan_params)

    respond_to do |format|
      if @flight_plan.save
        format.html { redirect_to @flight_plan, notice: 'Flight plan was successfully created.' }
        format.json { render :show, status: :created, location: @flight_plan }
      else
        format.html { render :new }
        format.json { render json: @flight_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flight_plans/1
  # PATCH/PUT /flight_plans/1.json
  def update
    respond_to do |format|
      if @flight_plan.update(flight_plan_params)
        format.html { redirect_to @flight_plan, notice: 'Flight plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight_plan }
      else
        format.html { render :edit }
        format.json { render json: @flight_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flight_plans/1
  # DELETE /flight_plans/1.json
  def destroy
    @flight_plan.destroy
    respond_to do |format|
      format.html { redirect_to flight_plans_url, notice: 'Flight plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight_plan
      @flight_plan = FlightPlan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flight_plan_params
      params.require(:flight_plan).permit(:final_x_location, :final_y_location)
    end
end

app/controllers/test_api_controller.rb
class TestApiController < ApplicationController
  def directions
    response = { "directions"=>
     %w[forward right forward forward forward left forward forward left right forward right forward forward right forward forward left]
    }
    render json: response
  end

  def location
    response = {
      "you said" => "x: #{params[:x]} , y: #{params[:y]}",
      "result" => "maybe you're right"
    }
    render json: response
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Rails standard helper module
module ApplicationHelper
end

app/helpers/flight_plans_helper.rb
module FlightPlansHelper
end

app/views/flight_plans/_form.html.erb
<%= form_with(model: flight_plan, local: true) do |form| %>
  <% if flight_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flight_plan.errors.count, "error") %> prohibited this flight_plan from being saved:</h2>

      <ul>
      <% flight_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :final_x_location %>
    <%= form.number_field :final_x_location %>
  </div>

  <div class="field">
    <%= form.label :final_y_location %>
    <%= form.number_field :final_y_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flight_plans/edit.html.erb
<h1>Editing Flight Plan</h1>

<%= render 'form', flight_plan: @flight_plan %>

<%= link_to 'Show', @flight_plan %> |
<%= link_to 'Back', flight_plans_path %>

app/views/flight_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flight Plans</h1>

<h2>
  <%= button_to 'Delete All', flight_plans_delete_all_url %>
  <p/>
  <%= form_with url: flight_plans_download_url, method: :post do |form| %>
    <%= form.label :email, "Email:" %>
    <%= form.email_field :email, value: @email %>
    <%= form.submit "Download" %>
  <% end %>
</h2>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Created At</th>
      <th>Directions</th>
      <th>Final x location</th>
      <th>Final y location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flight_plans.each do |flight_plan| %>
      <tr>
        <td><%= flight_plan.id %></td>
        <td><%= flight_plan.created_at %></td>
        <td><%= flight_plan.directions.count %></td>
        <td><%= flight_plan.final_x_location %></td>
        <td><%= flight_plan.final_y_location %></td>
        <td><%= flight_plan.directions.count > 0 ?
                    button_to('Run', run_flight_plan_path(flight_plan)) :
                  nil %></td>
        <td><%= flight_plan.final_x_location && flight_plan.final_y_location ?
                    button_to('Submit', submit_flight_plan_path(flight_plan, params: {email: @email})) :
                    nil %></td>
        <td><%= link_to 'Show', flight_plan %></td>
        <td><%= link_to 'Edit', edit_flight_plan_path(flight_plan) %></td>
        <td><%= link_to 'Destroy', flight_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight Plan', new_flight_plan_path %>

app/views/flight_plans/new.html.erb
<h1>New Flight Plan</h1>

<%= render 'form', flight_plan: @flight_plan %>

<%= link_to 'Back', flight_plans_path %>

app/views/flight_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Final x location:</strong>
  <%= @flight_plan.final_x_location %>
</p>

<p>
  <strong>Final y location:</strong>
  <%= @flight_plan.final_y_location %>
</p>

<%= link_to 'Edit', edit_flight_plan_path(@flight_plan) %> |
<%= link_to 'Back', flight_plans_path %>

app/views/flight_plans/submit.html.erb
<h2>Location Response was:</h2>
<%=  @api_response %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>